Sonia
Arquisoft/dede_es3c pull request #17
Opened 2022-02-10 08:18 UTC by SoniaFernandezCoto

Se han arreglado las erratas y añadido algunas especificaciones que faltaban

2022-02-10 11:45 UTC, NuriaIF approved these changes
Lo he revisado y lo veo correcto.

2022-02-10 18:53 UTC, UO232627 requested changes
Al final del Scenario de Privacy hay una errata: "...can be consulted CON it's pod..."

2022-02-10 18:54 UTC, UO232627 commented
De contenido lo veo bien

2022-02-13 17:57 UTC, NuriaIF commented
En el 6, hay que dividir DeDe en WebApp y RestApi

2022-02-15 19:41 UTC, NuriaIF requested changes
En el 3.1 falta una "s" en specific, y "querys" debería ser "queries". Por el resto lo veo bien 👍

2022-02-16 17:27 UTC, SergioArroni approved these changes
Revisado por el equipo

2022-02-16 17:34 UTC, merged