Añadido el apartado 2 de la documentación
Arquisoft/dede_es3c pull request #20
Opened 2022-02-12 11:13 UTC by UO232627

2022-02-13 18:22 UTC, SergioArroni commented
En el 2 yo añadiría Redux, en el punto 2.3

2022-02-13 18:25 UTC, SergioArroni commented
Arreglar sintaxis del doc

2022-02-13 18:31 UTC, NuriaIF commented
En el 6, cambiar nombre de la acción de "borrar el usuario" de la BD por "borrar la referencia al usuario".

2022-02-13 18:39 UTC, SergioArroni commented
En el 9 también vamos a usar Redux como patrón

2022-02-15 19:29 UTC, NuriaIF requested changes
Errores de formato:
- En el 2 aparece "##" al inicio de los subapartados, cambiar para que se vea bien
- En el 5 "== Whitebox Overall System" aparecen los "==" y donde se explican los dos tipos de actores sale de seguido en vez de en una lista (hacer un enter entre "application:" y "- User")

Errores de contenido:
- En el 6 estaría mejor añadir entity delante de WebApp y RestAPI, y añadir database delante de DataBase y UserPOD, por seguir un convenio para todos los diagramas.
- En el 9, erratas ortográficas: "languaje" debería ser language, "sinchrony" debería ser "synchrony". Yo creo que suena mejor poner "It is" en lugar de solo "Is" (columna disadvantadges)

2022-02-16 17:57 UTC, SergioArroni approved these changes
Revisado por el equipo

2022-02-16 18:00 UTC, merged